SELECT *from[dbo].[LITA DATA CLASS PROJECT FROM EXCEL TO SQL]


-------RETRIEVE THE TOTAL SALES FOR EACH PRODUCT CATEGORY-------

SELECT PRODUCT,SUM([Total_Sales]) AS [Total_Sales]
FROM [dbo].[LITA SALES DATA CP]
GROUP BY PRODUCT

---------FIND THE NUMBER OF SALES TRANSACTIONS IN EACH REGION--------

SELECT [Region], COUNT(OrderID) AS
NUMBER_OF_TRANSACTIONS
FROM [dbo].[LITA SALES DATA CP]
GROUP BY [Region]

--------FIND THE HIGHEST SELLING PRODUCT BY TOTAL SALES VALUE----

SELECT TOP(1) Product, SUM([Total_Sales]) AS TOTAL_SALES
FROM [dbo].[LITA SALES DATA CP]
GROUP BY PRODUCT
ORDER BY TOTAL_SALES DESC

------CALCULATE TOTAL REVENUE PER PRODUCT

SELECT PRODUCT,SUM([Total_Sales]) AS TOTAL_REVENUE
FROM [dbo].[LITA SALES DATA CP]
GROUP BY PRODUCT

---------CALCULATION OF MONTHLY SALES DATA FOR THE CURRENT YEAR-----

SELECT MONTH([OrderDate]) AS MONTH,
SUM ([Total_Sales]) AS MONTHLYSALESTOTAL
FROM [dbo].[LITA SALES DATA CP] WHERE YEAR([OrderDate])=2024
GROUP BY MONTH([OrderDate])
ORDER BY MONTH

---------CALCUALTION OF THE TOP 5 CUSTOMERS BY THEIR TOTAL PURCHASE AMOUNT-----

SELECT TOP(5) [Customer_Id],
SUM ([Total_Sales]) AS TOTALPURCHASEAMOUNT
 FROM [dbo].[LITA SALES DATA CP]
GROUP BY [Customer_Id]
ORDER BY TOTALPURCHASEAMOUNT DESC

----- PERCENTAGE OF TOTAL SALES CONTRIBUTED BY EACH REGION-----

SELECT [Region],
SUM ([Quantity] *[UnitPrice]) AS [Total_Sales],
(SUM ([Quantity] *[UnitPrice]) * 100.0) /
SUM(SUM([Quantity] *[UnitPrice])) OVER ()
AS PERCENTAGE_OF_SALES
FROM [dbo].[LITA SALES DATA CP]
GROUP BY REGION
ORDER BY PERCENTAGE_OF_SALES DESC

--------- IDENTIFY PRODUCT WITH NO SALES IN THE LAST QUARTER----

SELECT PRODUCT FROM [dbo].[LITA SALES DATA CP]
GROUP BY PRODUCT
HAVING SUM (CASE
WHEN [OrderDate] BETWEEN '2024-06-01' AND '2024-08-31'
THEN 1 ELSE 0 END)=0